<?php
namespace FormBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-16 at 09:48:47.
 */
class FieldOptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FieldOption
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FieldOption;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FormBuilder\FieldOption::setLabel
     */
    public function testSetLabel()
    {
        $this->object->setLabel('My Label');
        $this->assertEquals('My Label', $this->object->GetLabel(), 'Labels match.');
        $this->assertEmpty($this->object->GetValue(), 'Setting the label does not change the value.');
    }

    /**
     * @covers FormBuilder\FieldOption::getLabel
     */
    public function testGetLabel()
    {
        $this->object->setLabel('Another Label');
        $this->assertEquals('Another Label', $this->object->GetLabel(), 'Labels match.');
        $this->assertNull($this->object->GetValue(), 'Getting the label does not change the value.');
    }

    /**
     * @covers FormBuilder\FieldOption::setValue
     */
    public function testSetValue()
    {
        $this->object->SetValue('A Value');
        $this->assertEquals('A Value', $this->object->GetValue(), 'Values match');
        $this->assertEmpty($this->object->GetLabel(), 'Setting the value does not change the label');
    }

    /**
     * @covers FormBuilder\FieldOption::getValue
     */
    public function testGetValue()
    {
        $this->object->SetValue('A Value');
        $this->assertEquals('A Value', $this->object->GetValue(), 'Values match');
        $this->assertEmpty($this->object->GetLabel(), 'Getting the value does not change the label');
    }
}
