<?php
namespace FormBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-16 at 09:48:47.
 */
class FieldOptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FieldOption
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FieldOption;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FormBuilder\FieldOption::setLabel
     * @todo   Implement testSetLabel().
     */
    public function testSetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FieldOption::getLabel
     * @todo   Implement testGetLabel().
     */
    public function testGetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FieldOption::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FieldOption::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
