<?php
namespace FormBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-16 at 09:48:09.
 */
class FormBuilderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FormBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FormBuilder('phpunit', 'PHPUnit Test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FormBuilder\FormBuilder::createFieldset
     * @todo   Implement testCreateFieldset().
     */
    public function testCreateFieldset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FormBuilder::export
     * @todo   Implement testExport().
     */
    public function testExport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
