<?php
namespace FormBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-16 at 09:49:21.
 */
class FormFieldTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FormField
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FormField('text', 'field_name', 'field_id');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FormBuilder\FormField::getName
     */
    public function testGetName()
    {
        $this->assertEquals('field_name', $this->object->getName(), 'Field names must match.');
    }

    /**
     * @covers FormBuilder\FormField::getID
     */
    public function testGetID()
    {
        $this->assertEquals('field_id', $this->object->getID(), 'Field ids must match.');
    }

    /**
     * @covers FormBuilder\FormField::setLabel
     */
    public function testSetLabel()
    {
        $this->assertEmpty($this->object->getLabel(), 'Label must be empty prior to setting.');
        $this->object->setLabel('test label');
        $this->assertEquals('test label', $this->object->getLabel(), 'Field labels must match.');
        $this->assertEmpty($this->object->getDescription(), 'Description must remain empty when description updated.');
    }

    /**
     * @covers FormBuilder\FormField::getLabel
     */
    public function testGetLabel()
    {
        $this->assertEmpty($this->object->getLabel(), 'Label must be empty prior to setting.');
        $this->object->setLabel('label test');
        $this->assertEquals('label test', $this->object->getLabel(), 'Field labels must match.');
        $this->assertEmpty($this->object->getDescription(), 'Description must remain empty when description updated.');
    }

    /**
     * @covers FormBuilder\FormField::setDescription
     */
    public function testSetDescription()
    {
        $this->assertEmpty($this->object->getDescription(), 'Description must be empty prior to setting.');
        $this->object->setDescription('test description');
        $this->assertEquals('test description', $this->object->getDescription(), 'Field descriptions must match.');
        $this->assertEmpty($this->object->getLabel(), 'Label must remain empty when description updated.');
    }

    /**
     * @covers FormBuilder\FormField::getDescription
     */
    public function testGetDescription()
    {
        $this->assertEmpty($this->object->getDescription(), 'Description must be empty prior to setting.');
        $this->object->setDescription('description test');
        $this->assertEquals('description test', $this->object->getDescription(), 'Field descriptions must match.');
        $this->assertEmpty($this->object->getLabel(), 'Label must remain empty when description updated.');
    }

    /**
     * @covers FormBuilder\FormField::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FormField::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FormField::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FormField::createOption
     * @todo   Implement testCreateOption().
     */
    public function testCreateOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FormField::getOptions
     * @todo   Implement testGetOptions().
     */
    public function testGetOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FormField::setRequired
     * @todo   Implement testSetRequired().
     */
    public function testSetRequired()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormBuilder\FormField::getRequired
     * @todo   Implement testGetRequired().
     */
    public function testGetRequired()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
